[features]
seeds = false
skip-lint = false
[programs.localnet]
coral_multisig = "Gj7KornahQdBkwxvobJSVNfp9e9VotKWQkD6fVra5zzg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/multisig.ts"
