[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_timelock = "TiMEYuk7rCBAFYMvhN3hae9PRc1NUYL71Zu3MCaCBVe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/solana_timelock.ts"
