name: anchor-test
on:
  push:
  pull_request:

jobs:
  run-anchor-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: metadaobuilders/anchor-test@v1.2
        with:
            anchor-version: '0.26.0'
            solana-cli-version: '1.14.17'
